-- Migration number: 0001 generated by teenybase on 2026-06-04T19:05:45.778Z. Do not modify this file.

CREATE TABLE vocabulary (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	polish TEXT NOT NULL, 
	translation TEXT NOT NULL, 
	transcription TEXT, 
	part_of_speech TEXT, 
	example TEXT, 
	examples_list JSON, 
	category TEXT NOT NULL, 
	level TEXT, 
	image_name TEXT
);
CREATE TRIGGER tgr_vocabulary_raise_on_created_update BEFORE UPDATE OF created ON vocabulary BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_vocabulary_update_updated_on_update AFTER UPDATE ON vocabulary BEGIN UPDATE vocabulary SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;