-- Migration number: 0002 generated by teenybase on 2026-06-04T19:05:45.778Z. Do not modify this file.

CREATE TABLE grammar_lessons (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	lesson_id TEXT NOT NULL, 
	title TEXT NOT NULL, 
	description TEXT, 
	level TEXT NOT NULL, 
	order_index INTEGER DEFAULT 0, 
	steps JSON NOT NULL
);
CREATE TRIGGER tgr_grammar_lessons_raise_on_created_update BEFORE UPDATE OF created ON grammar_lessons BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_grammar_lessons_update_updated_on_update AFTER UPDATE ON grammar_lessons BEGIN UPDATE grammar_lessons SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;