-- Migration number: 0003 generated by teenybase on 2026-06-05T21:46:57.101Z. Do not modify this file.

ALTER TABLE vocabulary
                    ADD COLUMN rank_35f34 INTEGER DEFAULT 0;
ALTER TABLE vocabulary RENAME COLUMN rank_35f34 TO rank;