-- Migration number: 0004 generated by teenybase on 2026-06-05T22:08:14.311Z. Do not modify this file.

ALTER TABLE vocabulary
                    ADD COLUMN inflections_459a6 JSON;
ALTER TABLE vocabulary RENAME COLUMN inflections_459a6 TO inflections;