-- Migration number: 0005 generated by teenybase on 2026-06-07T23:57:30.777Z. Do not modify this file.

CREATE TABLE review_logs (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	user_id TEXT NOT NULL REFERENCES users(id), 
	card_id TEXT NOT NULL, 
	rating INTEGER NOT NULL CHECK(rating IN (1, 2, 3, 4)), 
	review_date DATETIME NOT NULL, 
	review_duration_ms INTEGER DEFAULT 0
);
CREATE UNIQUE INDEX idx_review_logs_review_logs_user_card_date_unique ON review_logs (user_id, card_id, review_date);
CREATE INDEX idx_review_logs_review_logs_user_date ON review_logs (user_id, review_date);
CREATE TRIGGER tgr_review_logs_raise_on_created_update BEFORE UPDATE OF created ON review_logs BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;