-- Migration number: 0006 generated by teenybase on 2026-06-08T10:48:54.234Z. Do not modify this file.

CREATE TABLE fsrs_params (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	user_id TEXT UNIQUE NOT NULL REFERENCES users(id), 
	parameters JSON NOT NULL CHECK(json_valid(parameters)), 
	desired_retention REAL NOT NULL, 
	learning_steps JSON NOT NULL CHECK(json_valid(learning_steps)), 
	relearning_steps JSON NOT NULL CHECK(json_valid(relearning_steps))
);
CREATE TRIGGER tgr_fsrs_params_raise_on_created_update BEFORE UPDATE OF created ON fsrs_params BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_fsrs_params_update_updated_on_update AFTER UPDATE ON fsrs_params BEGIN UPDATE fsrs_params SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;