-- Migration number: 0007 generated by teenybase on 2026-06-24T14:23:40.245Z. Do not modify this file.

CREATE TABLE exam_sessions (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	session_id TEXT NOT NULL, 
	start_date TEXT NOT NULL, 
	end_date TEXT NOT NULL, 
	levels JSON NOT NULL
);
CREATE TRIGGER tgr_exam_sessions_raise_on_created_update BEFORE UPDATE OF created ON exam_sessions BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_exam_sessions_update_updated_on_update AFTER UPDATE ON exam_sessions BEGIN UPDATE exam_sessions SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;