-- Migration number: 0008 generated by teenybase on 2026-06-25T16:00:31.007Z. Do not modify this file.

CREATE TABLE writing_attempts (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	user_id TEXT NOT NULL, 
	task_id TEXT NOT NULL, 
	overall_percent INTEGER DEFAULT 0, 
	passed INTEGER DEFAULT 0
);
CREATE TRIGGER tgr_writing_attempts_raise_on_created_update BEFORE UPDATE OF created ON writing_attempts BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_writing_attempts_update_updated_on_update AFTER UPDATE ON writing_attempts BEGIN UPDATE writing_attempts SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;