-- Migration number: 0009 generated by teenybase on 2026-06-28T23:05:45.207Z. Do not modify this file.

CREATE TABLE leaderboard (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	user_id TEXT UNIQUE NOT NULL, 
	display_name TEXT NOT NULL, 
	xp INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_leaderboard_leaderboard_xp ON leaderboard (xp);
CREATE TRIGGER tgr_leaderboard_raise_on_created_update BEFORE UPDATE OF created ON leaderboard BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_leaderboard_update_updated_on_update AFTER UPDATE ON leaderboard BEGIN UPDATE leaderboard SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;